# User config
author: "Zhenyu Zheng"
title: "Arm Datacenter Ecosystem Landscape"
tagline: "Arm CI Landscape"
description: "Arm CI Landscape"
keywords: "Arm, CI, Landscape"
email: "zheng.zhenyu@outlook.com"
github: "https://kunpengcompute.github.io/"
issue: "https://github.com/kunpengcompute/arm-landscape/issues"

# Site config
baseurl: "/arm-landscape"
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
